//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiamiPalms.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Statistics
    {
        public int Id { get; set; }
        public int PlayerId { get; set; }
        public decimal PointsPG { get; set; }
        public decimal AssistsPG { get; set; }
        public decimal ReboundsPG { get; set; }
    
        public virtual Player Player { get; set; }
    }
}
