//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiamiPalms.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        public Team()
        {
            this.Game = new HashSet<Game>();
            this.Game1 = new HashSet<Game>();
            this.Player = new HashSet<Player>();
            this.User = new HashSet<User>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public byte[] Photo { get; set; }
    
        public virtual ICollection<Game> Game { get; set; }
        public virtual ICollection<Game> Game1 { get; set; }
        public virtual ICollection<Player> Player { get; set; }
        public virtual ICollection<User> User { get; set; }
    }
}
